"""referral system upgrade

Revision ID: 5de189770cf2
Revises: 15db6b329d28
Create Date: 2025-08-30 15:07:37.750455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '5de189770cf2'
down_revision: Union[str, None] = '15db6b329d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'referral_earnings' in existing_tables:
        print("Table 'referral_earnings' already exists, skipping creation.")
        return

    op.create_table('referral_earnings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
                    sa.Column('referral_id', sa.BigInteger(), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
                    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['referral_id'], ['users.telegram_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['referrer_id'], ['users.telegram_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_referral_earnings_referral_created', 'referral_earnings', ['referral_id', 'created_at'],
                    unique=False)
    op.create_index(op.f('ix_referral_earnings_referral_id'), 'referral_earnings', ['referral_id'], unique=False)
    op.create_index('ix_referral_earnings_referrer_created', 'referral_earnings', ['referrer_id', 'created_at'],
                    unique=False)
    op.create_index(op.f('ix_referral_earnings_referrer_id'), 'referral_earnings', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_earnings_referrer_id'), table_name='referral_earnings')
    op.drop_index('ix_referral_earnings_referrer_created', table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_referral_id'), table_name='referral_earnings')
    op.drop_index('ix_referral_earnings_referral_created', table_name='referral_earnings')
    op.drop_table('referral_earnings')
    # ### end Alembic commands ###
