"""unfinished_operations drop

Revision ID: c720febc8cd2
Revises: 3f9d1b7a4a6c
Create Date: 2025-08-17 18:05:48.615967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c720febc8cd2'
down_revision = "3f9d1b7a4a6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unfinished_operations_operation_id', table_name='unfinished_operations')
    op.drop_index('ix_unfinished_operations_user_id', table_name='unfinished_operations')
    op.drop_table('unfinished_operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unfinished_operations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('operation_value', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('operation_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unfinished_operations_user_id', 'unfinished_operations', ['user_id'], unique=False)
    op.create_index('ix_unfinished_operations_operation_id', 'unfinished_operations', ['operation_id'], unique=1)
    # ### end Alembic commands ###
